Move gem-rehash monkey patch
rbenv/rbenv pull request #1541
Opened 2023-11-30 21:18 UTC by benmelz

The `rubygems_plugin.rb` file doesn't get loaded until after `Bundler::Installer.install` is called, so target `Bundler::Installer#install` to fix invocation order issues.

Closes #1540

2023-12-06 10:47 UTC, mislav reviewed
Thanks for tracking this down and for proposing a solution!

`rbenv rehash` should be started concurrently by multiple threads at the same time. Depending on the `bundle install --jobs` setting, multiple gems that each install their executables could be installed at the same time. Could you test to see if the `install` instance method is being invoked per each gem and could potentially be invoked concurrently? In such case, there should be a mutex around `rbenv rehash`.

2023-12-06 15:27 UTC, benmelz commented
> Could you test to see if the install instance method is being invoked per each gem and could potentially be invoked concurrently? In such case, there should be a mutex around rbenv rehash.

The parallelization [happens within `Bundler::Installer#install`](https://github.com/rubygems/rubygems/blob/9766fa6ba4619571feb13fd30e199c62bcc784f9/bundler/lib/bundler/installer.rb#L201), so the wrapper should still be run once, sequentially after everything has been spawned and waited on in terms of parallelization.

> Alternatively, would it be an option to hook into Plugin::Events::GEM_AFTER_INSTALL_ALL? I think that such an approach could last longer than any form of monkey patching.

So I actually initially took this approach on [this branch which I just pushed up](https://github.com/benmelz/rbenv/tree/gem-rehash-bundler-plugin). I did manage to get it mostly working, but stopped due to some asterisks:
- The bundler plugin API is heavily tied to the concept that gems provide plugins and plugins provide hooks (like `after-install-all`) - even if you try to programmatically add your own hooks, bundler [will refuse to run them unless there's an associated plugin](https://github.com/rubygems/rubygems/blob/46585225c34676d605daad05604a0dde11623509/bundler/lib/bundler/plugin.rb#L228). I _was_ able to [trick bundler in to thinking a non-existing gem provided our rehash plugin](https://github.com/benmelz/rbenv/blob/c25bbc358c0838b737d87f494c15cef491a0ef15/rbenv.d/exec/gem-rehash/rubygems_plugin.rb#L17) by using an ugly hack (the `Struct`). That being said, you _could_ look at it as an ugly hack in a less important (thus more prone to changes) part of private API.
- And then additional reasons I discounted this when I first wrote the branch - there were some weird console output related to the plugin registration, and I was observing some odd files being created in local `.bundle` directories as well. Of course I'm not observing that behavior now, though, so there might have been something else going on.

If the former sounds okay to you though, I'd be happy to swap the implementations out. Just have to smooth out some more stuff with the "detect if the # of bins changed" logic.

2023-12-06 21:52 UTC, mislav commented
> * The bundler plugin API is heavily tied to the concept that gems provide plugins and plugins provide hooks (like `after-install-all`) - even if you try to programmatically add your own hooks, bundler will refuse to run them unless there's an associated plugin.

Ah, that does sound like some hoops to jump through and not at all simpler than monkeypatching. Thanks for giving it a shot!

2023-12-06 22:02 UTC, mislav requested changes

2023-12-06 22:02 UTC, mislav commented on rbenv.d/exec/gem-rehash/rubygems_plugin.rb
> +if defined?(Bundler::Installer) && Bundler::Installer.methods.include?(:install) && !Bundler::Installer.methods.include?(:install_without_rbenv_rehash)
`Class.methods.include?` checks for the presence of a class method, but since we switched to monkeypatching `install` on the instance level, we should be checking method presence on the instance too

```suggestion
if defined?(Bundler::Installer) && Bundler::Installer.method_defined?(:install) && !Bundler::Installer.method_defined?(:install_without_rbenv_rehash)
```

2023-12-09 20:13 UTC, mislav approved these changes
Thank you!

2023-12-09 20:14 UTC, merged